### PR TITLE
web-ui: added color effect on newest blocks (fixes #20)

### LINKED ISSUE #20: Improve the latest blocks view
The latest blocks view could be improved.

### Expected behavior

When there is a new block discovered, we add a small color effect on it to make it simpler to be aware of, example:
new-block

### Actual behavior
When a new block is discovered, we just update the block list with no effects at all.

### Steps to reproduce the behavior

Go to https://xsnexplorer.io/ and wait for a minute or two to see a new block.

### PR DESCRIPTION
**Pull request by mario128mex**
Problem

On latest block view, the newest blocks were hard to notice
Solution

Added a color effect on newest blocks

Result

ezgif-4-e740ffedcb

### CODE REVIEW

File: web-ui/src/app/components/latest-blocks/latest-blocks.component.ts [hunk 1]
```diff
@@ -70,9 +72,30 @@ export class LatestBlocksComponent implements OnInit, OnDestroy {
   }
 
   private onBlockRetrieved(response: Block[]) {
+    this.countNewestBlocks(response);
+    this.latestBlock = response[0];
     this.blocks = response;
   }
 
+  private countNewestBlocks(newBlocks: Block[]) {
```
Comment (AlexITC) [inline web-ui/src/app/components/latest-blocks/latest-blocks.component.ts]: I would avoid functions with side effects as much as possible, as a example, you mutating the `totalNewestBlocks`, instead you can return the number of new blocks and do whatever you want with the number, think about which version would be simpler to test.

File: web-ui/src/app/components/latest-blocks/latest-blocks.component.ts [hunk 2]
```diff
@@ -70,9 +72,30 @@ export class LatestBlocksComponent implements OnInit, OnDestroy {
...
+    if (!this.blocks) {
+      return;
+    }
+
+    const lastestBlockHash: string = this.latestBlock.hash;
```
Comment (AlexITC) [inline web-ui/src/app/components/latest-blocks/latest-blocks.component.ts]: I would just pass this as an argument, as a hint, the `height` attribute from a block is just the block number and it is unique, it should be simpler to use that instead of the block hash, again, think on simplicity to test.

File: web-ui/src/app/components/latest-blocks/latest-blocks.component.ts [hunk 3]
```diff
@@ -70,9 +72,30 @@ export class LatestBlocksComponent implements OnInit, OnDestroy {
...
+    let totalNewBlocks = 0;
+
+    for (let i = 0; i < newBlocks.length; i++) {
```
Comment (AlexITC) [inline web-ui/src/app/components/latest-blocks/latest-blocks.component.ts]: A loop is error prone, use collection transformation functions instead, like `map` and `filter`, if you use the latest block height, it is simple to filter by the blocks having a higher height.

File: web-ui/src/app/components/latest-blocks/latest-blocks.component.ts [hunk 4]
```diff
@@ -92,4 +115,8 @@ export class LatestBlocksComponent implements OnInit, OnDestroy {
   age(block: Block): string {
     return '';
   }
+
+  isBlockRecent(index: number): boolean {
```
Comment (AlexITC) [inline web-ui/src/app/components/latest-blocks/latest-blocks.component.ts]: In my opinion, checking this by an index is error prone, angular allows you to pass the block object as an argument to the function, on the testability side, it would be simpler to receive both arguments instead of referencing a mutable variable.

File: web-ui/src/app/components/latest-blocks/latest-blocks.component.ts [hunk 5]
```diff
@@ -70,9 +72,30 @@ export class LatestBlocksComponent implements OnInit, OnDestroy {
   }
 
   private onBlockRetrieved(response: Block[]) {
+    this.countNewestBlocks(response);
```
Comment (AlexITC) [inline web-ui/src/app/components/latest-blocks/latest-blocks.component.ts]: What I would do is to get the list of new blocks and store them in a mutable variable, something like `this.newBlocks = this.getNewBlocks(this.blocks || [], response)` with a function like `private getNewBlocks(currentBlocks: Block[], latestBlocks: Block[]): Block[]`.

This might give the effect that the initial load will paint all blocks which should be acceptable.

File: web-ui/src/app/components/latest-blocks/latest-blocks.component.ts [hunk 6]
```diff
@@ -70,9 +72,30 @@ export class LatestBlocksComponent implements OnInit, OnDestroy {
...
+    this.latestBlock = response[0];
```
Comment (AlexITC) [inline web-ui/src/app/components/latest-blocks/latest-blocks.component.ts]: This should not be required at all.

File: web-ui/src/app/components/latest-blocks/latest-blocks.component.ts [hunk 7]
```diff
@@ -26,6 +26,8 @@ import { ErrorService } from '../../services/error.service';
 export class LatestBlocksComponent implements OnInit, OnDestroy {
 
   blocks: Block[];
+  private totalNewestBlocks: number;
```
Comment (AlexITC) [inline web-ui/src/app/components/latest-blocks/latest-blocks.component.ts]: I would define `private newBlocks: Block[];` instead.

File: web-ui/src/app/components/latest-blocks/latest-blocks.component.ts [hunk 8]
```diff
@@ -26,6 +26,8 @@ import { ErrorService } from '../../services/error.service';
...
+  private latestBlock: Block;
```
Comment (AlexITC) [inline web-ui/src/app/components/latest-blocks/latest-blocks.component.ts]: This should not be required at all.

File: web-ui/src/app/components/latest-blocks/latest-blocks.component.html [hunk 9]
```diff
@@ -26,7 +26,7 @@ <h4>{{'message.loadingLatestBlocks' | translate}}</h4>
           </thead>
 
           <tbody>
-            <tr *ngFor="let item of blocks">
+            <tr *ngFor="let item of blocks; let i = index" [ngClass]="{ 'latest-block': isBlockRecent(i) }">
```
Comment (AlexITC) [inline web-ui/src/app/components/latest-blocks/latest-blocks.component.html]: The index is not required, you can just call `isNewBlock(item)` where that function returns `true` if the item hash or height exists in the `newBlocks` variable, this can be done easily by the filtering over it.

File: web-ui/src/app/components/latest-blocks/latest-blocks.component.css [hunk 10]
```diff
@@ -0,0 +1,9 @@
+.latest-block {
```
Comment (AlexITC) [inline web-ui/src/app/components/latest-blocks/latest-blocks.component.css:1]: Well done in all the file.

**Review by AlexITC — CHANGES_REQUESTED** [review]

File: web-ui/src/app/components/latest-blocks/latest-blocks.component.ts [hunk 11]
```diff
@@ -72,28 +71,16 @@ export class LatestBlocksComponent implements OnInit, OnDestroy {
...
-    for (let i = 0; i < newBlocks.length; i++) {
-      if (newBlocks[i].hash === lastestBlockHash) {
-        break;
-      }
-
-      totalNewBlocks++;
-    }
-
-    this.totalNewestBlocks = totalNewBlocks;
+    return newBlocks.filter(newBlock => newBlock.height > this.blocks[0].height);
```
Comment (AlexITC) [inline web-ui/src/app/components/latest-blocks/latest-blocks.component.ts]: you are assuming that the blocks are in certain order, while today that's true, we don't know if it would be tomorrow. you can easily get the current latest block height and compare against that.

File: web-ui/src/app/components/latest-blocks/latest-blocks.component.ts [hunk 12]
```diff
@@ -72,28 +71,16 @@ export class LatestBlocksComponent implements OnInit, OnDestroy {
...
   private onBlockRetrieved(response: Block[]) {
-    this.countNewestBlocks(response);
-    this.latestBlock = response[0];
+    this.newBlocks = this.getNewBlocks(response);
     this.blocks = response;
   }
 
-  private countNewestBlocks(newBlocks: Block[]) {
+  private getNewBlocks(newBlocks: Block[]): Block[] {
     if (!this.blocks) {
```
Comment (AlexITC) [inline web-ui/src/app/components/latest-blocks/latest-blocks.component.ts]: again, this is harder to test than just passing the required argument to the function, please stop using global state.

Comment (AlexITC) [inline web-ui/src/app/components/latest-blocks/latest-blocks.component.ts]: in fact, if you receive the latest block height as an argument, this conditional will be useless.

**Review by AlexITC — CHANGES_REQUESTED** [review]

File: web-ui/src/app/components/latest-blocks/latest-blocks.component.ts [hunk 13]
```diff
@@ -26,6 +26,7 @@ import { ErrorService } from '../../services/error.service';
 export class LatestBlocksComponent implements OnInit, OnDestroy {
 
   blocks: Block[];
+  private latestBlockHeight: number;
```
Comment (AlexITC) [inline web-ui/src/app/components/latest-blocks/latest-blocks.component.ts]: please, initialize this to `0` or `-1` to avoid undefined issues.

File: web-ui/src/app/components/latest-blocks/latest-blocks.component.ts [hunk 14]
```diff
@@ -70,6 +71,7 @@ export class LatestBlocksComponent implements OnInit, OnDestroy {
   }
 
   private onBlockRetrieved(response: Block[]) {
+    this.latestBlockHeight = this.blocks ? this.blocks[0].height : 0;
```
Comment (AlexITC) [inline web-ui/src/app/components/latest-blocks/latest-blocks.component.ts]: please just get the maximum instead.
